services:
  pokemon-deck-builder:
    build:
      context: .
      target: production
    ports:
      - "3000:3001"
    volumes:
      - ./server/db:/app/server/db
    environment:
      - NODE_ENV=production
      - PORT=3001
