export type Language = 'en' | 'pt' | 'es';

export const translations = {
  en: {
    appTitle: 'Have Want BR - PokéDeck Builder',
    decks: 'My Decks',
    createDeck: 'Create New Deck',
    deckName: 'Deck Name',
    cancel: 'Cancel',
    create: 'Create',
    rename: 'Rename',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    searchCards: 'Search cards...',
    noCardsFound: 'No cards found.',
    deckBuilder: 'Deck Builder',
    backToDecks: 'Back to Decks',
    cardsInDeck: 'Cards in Deck',
    addCard: 'Add',
    removeCard: 'Remove',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    confirmDelete: 'Are you sure you want to delete this deck?',
    saveSuccess: 'Deck saved successfully!',
    renameDeck: 'Rename Deck',
    deckEmpty: 'Your deck is empty. Add some cards!',
    loading: 'Loading...',
    totalCards: 'Total Cards',
    searchPlaceholder: 'Type a Pokémon name...',
    share: 'Share',
    copyImportLink: 'Copy Import Link',
    copyAsText: 'Copy as Text',
    downloadImage: 'Download Image',
    linkCopied: 'Link copied to clipboard!',
    textCopied: 'Text copied to clipboard!',
    setCover: 'Set as Cover',
    favorites: 'Favorites',
    addFavorite: 'Add Favorite',
    removeFavorite: 'Remove Favorite',
    addToDeck: 'Add to Deck',
    noFavorites: 'No favorite cards yet',
    noFavoritesDesc: 'Click on a card to view its details and add it to your favorites.',
    format: 'Format',
    standard: 'Standard',
    expanded: 'Expanded',
    glc: 'GLC',
    none: 'No Format',
  },
  pt: {
    appTitle: 'Have Want BR - Construtor de PokéDeck',
    decks: 'Meus Decks',
    createDeck: 'Criar Novo Deck',
    deckName: 'Nome do Deck',
    cancel: 'Cancelar',
    create: 'Criar',
    rename: 'Renomear',
    delete: 'Excluir',
    edit: 'Editar',
    save: 'Salvar',
    searchCards: 'Pesquisar cartas...',
    noCardsFound: 'Nenhuma carta encontrada.',
    deckBuilder: 'Construtor de Deck',
    backToDecks: 'Voltar aos Decks',
    cardsInDeck: 'Cartas no Deck',
    addCard: 'Adicionar',
    removeCard: 'Remover',
    themeLight: 'Modo Claro',
    themeDark: 'Modo Escuro',
    confirmDelete: 'Tem certeza que deseja excluir este deck?',
    saveSuccess: 'Deck salvo com sucesso!',
    renameDeck: 'Renomear Deck',
    deckEmpty: 'Seu deck está vazio. Adicione algumas cartas!',
    loading: 'Carregando...',
    totalCards: 'Total de Cartas',
    searchPlaceholder: 'Digite o nome de um Pokémon...',
    share: 'Compartilhar',
    copyImportLink: 'Copiar Link de Importação',
    copyAsText: 'Copiar como Texto',
    downloadImage: 'Baixar Imagem',
    linkCopied: 'Link copiado para a área de transferência!',
    textCopied: 'Texto copiado para a área de transferência!',
    setCover: 'Definir como Capa',
    favorites: 'Favoritos',
    addFavorite: 'Adicionar aos Favoritos',
    removeFavorite: 'Remover dos Favoritos',
    addToDeck: 'Adicionar ao Deck',
    noFavorites: 'Nenhuma carta favorita ainda',
    noFavoritesDesc: 'Clique em uma carta para ver seus detalhes e adicioná-la aos seus favoritos.',
    format: 'Formato',
    standard: 'Padrão (Standard)',
    expanded: 'Expandido (Expanded)',
    glc: 'GLC',
    none: 'Sem Formato',
  },
  es: {
    appTitle: 'Have Want BR - Constructor de PokéDeck',
    decks: 'Mis Mazos',
    createDeck: 'Crear Nuevo Mazo',
    deckName: 'Nombre del Mazo',
    cancel: 'Cancelar',
    create: 'Crear',
    rename: 'Renombrar',
    delete: 'Eliminar',
    edit: 'Editar',
    save: 'Guardar',
    searchCards: 'Buscar cartas...',
    noCardsFound: 'No se encontraron cartas.',
    deckBuilder: 'Constructor de Mazo',
    backToDecks: 'Volver a los Mazos',
    cardsInDeck: 'Cartas en el Mazo',
    addCard: 'Añadir',
    removeCard: 'Quitar',
    themeLight: 'Modo Claro',
    themeDark: 'Modo Oscuro',
    confirmDelete: '¿Estás seguro de que quieres eliminar este mazo?',
    saveSuccess: '¡Mazo guardado con éxito!',
    renameDeck: 'Renombrar Mazo',
    deckEmpty: 'Tu mazo está vacío. ¡Añade algunas cartas!',
    loading: 'Cargando...',
    totalCards: 'Total de Cartas',
    searchPlaceholder: 'Escribe el nombre de un Pokémon...',
    share: 'Compartir',
    copyImportLink: 'Copiar Enlace de Importación',
    copyAsText: 'Copiar como Texto',
    downloadImage: 'Descargar Imagen',
    linkCopied: '¡Enlace copiado al portapapeles!',
    textCopied: '¡Texto copiado al portapapeles!',
    setCover: 'Establecer como Portada',
    favorites: 'Favoritos',
    addFavorite: 'Añadir a Favoritos',
    removeFavorite: 'Quitar de Favoritos',
    addToDeck: 'Añadir al Mazo',
    noFavorites: 'Aún no hay cartas favoritas',
    noFavoritesDesc: 'Haz clic en una carta para ver sus detalles y añadirla a tus favoritos.',
    format: 'Formato',
    standard: 'Estándar',
    expanded: 'Expandido',
    glc: 'GLC',
    none: 'Sin Formato',
  }
};
